config = {
    ESX = "esx:getSharedObject",
    notif = "Appuyez sur [~HC_164~E~s~] pour accéder au shop ~HUD_COLOUR_GREEN~~BLIP_heist~~s~",
    typemarker = 6,
    taillemarker = {x = 0.8, y = 1.2, z = 0.8},
    colormarker = {r = 0, g = 0, b = 255, a = 250},
    typemarker2 = 29,
    colormarker2 = {r = 0, g = 0, b = 255, a = 250},
    taillemarker2 = {x = 0.6, y = 0.8, z = 0.6},
    Informations = {
        TitreMenu = "Supérette",
        SousMenu = "CatÉgories",
        SousMenu1 = "Panier",
        List = 1,
        listmoney = 1,
        totalprix = 0,
        panier = {},
        ListePayement = {"espèces","banque"},
        ListeCategories = {
            "Nourritures",
            "Boissons",
            "Autres"
        },
        addpanier = "Vous avez ajouté ~y~",
        PrixTotal = "Prix total",
        couleurvert = "~HC_25~",
        KeyBoard = "Nombres ?",
        Notification = "~r~Montant Invalide",
        Notification2 = "~r~Vous ne pouvez pas prendre plus de ",
        Notification3 = "Supprimer cet article ? (~b~OUI~s~/~r~NON~s~)",
        Notification4 = "~r~Vous avez annulé cette demande",
        Button = {
            categorie = "Catégories",
            acceder = "~HC_175~Accéder au panier~s~",
            separator = "~HC_162~Votre panier est vide~s~",
            separator1 = "↓ Votre panier ↓",
            acheter = "Acheter les articles~s~",
            vider = "~HC_162~Vider le panier~s~",
            payer = "Payer en espèces",
            payer2 = "Payer en carte bancaire",
        },

    },
    Shop = {
        Nourritures = {
            {item = "bread", label = "Pain", price = 1, maxitem = 10},
            {item = "sandwich", label = "Sandwich", price = 1, maxitem = 10},
        },
        Boissons = {
            {item = "water", label = "Eau", price = 1, maxitem = 10},
            {item = "coca", label = "Coca", price = 2, maxitem = 10},
        },
        Autres = {
            {item = "phone", label = "Téléphone", price = 1, maxitem = 10},
            {item = "sim", label = "Carte Sim", price = 1, maxitem = 10},
        },
    },
    Positions = {
        {pos = vector3(25.6523, -1346.8371, 28.4970), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(-47.7705, -1757.2098, 28.45), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1135.96, -981.61, 45.42), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(373.875, 325.896, 102.600), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(-1223.33, -906.9619, 11.40), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1166.0019, 2708.9914, 37.25), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(2557.458, 382.282, 107.650), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(2678.916, 3280.671, 54.260), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1729.12, 6414.91, 34.1), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(-1487.553, -379.107, 39.163), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1392.562, 3604.684, 33.999), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1163.373, -323.801, 68.210), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(-707.501, -914.260, 18.280), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(-1820.523, 792.518, 137.14), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
        {pos = vector3(1698.388, 4924.404, 41.1), BlipSprite = 59, BlipScale = 0.7, BlipDisplay = 4, BlipColor = 25, BlipLabel = "Supérette", afficherblip = true},
    }
}